### ISSUE TITLE
Incompatible with opitfine and optifabric

### ISSUE THREAD

**Issue by LordOfEdge** [shedaniel/Materialisation#1]
https://pastebin.com/XdMcmdzz

**Comment by shedaniel** [comment]
This will not be fixed, unless I have time to invest into looking into how optifine affects my mixin.

**Comment by shedaniel** [comment]
Materialisation 0.3.0 is updated with semi-optifine support, the mod won't crash anymore but tool durability bar support will be gone.

**Comment by shedaniel** [comment]
Whatever, starting from Materialisation 0.3.2, full optifine support has been added with **hax**, please take good care with it.
