### ISSUE TITLE
Update to Cotton Resources 1.3

### ISSUE THREAD

**Issue by ExoFrece** [shedaniel/Materialisation#10]
From 1.3, Cotton Resources has an Ore Voting please Add this to generate the ore.
or for easy integration please consult Cotton Discord: https://discord.gg/Mr3uWXH

Thank you for your hard work :)

**Comment by shedaniel** [comment]
I won't do ore voting. But will change to detect if the ore is enabled. Also I am in that discord already :)

EDIT: No I think I won't change anything now as even I stated that this mod has combat with Cotton Resources, it is basically a compat to all metal using the same tag (e.g. Refined Machinery)

**Comment by shedaniel** [comment]
Update: I will do ore voting

**Comment by LemmaEOF** [comment]
Another note: Mercury is gone in C-R now.

**Comment by shedaniel** [comment]
Done in v1.0
