### ISSUE TITLE
Hammer destroying adjacent bedrock blocks

### ISSUE THREAD

**Issue by MrNiceforest** [shedaniel/Materialisation#12]
While using any hammer from the mod (regardless of mining level), it won't destroy adjacent blocks like dirt or gravel (as probably intended), however it will destroy adjacent bedrock blocks in the 3x3 area if a valid block like cobblestone is mined - I don't this is intended and should perhaps be fixed.

Minecraft: v1.14.4 release
Fabric: v0.4.8-build 158
Materialisation: v0.5.2
Cotton Resources: v1.4.0+1.14.4

![2019-07-28_11 08 53](https://user-images.githubusercontent.com/30006052/62004694-9057eb80-b128-11e9-9e42-1f141bacfcaf.jpg)
![2019-07-28_11 08 57](https://user-images.githubusercontent.com/30006052/62004696-951c9f80-b128-11e9-91a7-73569eb93073.jpg)

**Comment by shedaniel** [comment]
this is bruh moment i need to get this fixed
