### ISSUE TITLE
server not launching due to many class exceptions from multiple mod(1.14.4 fabric)

### ISSUE THREAD

**Issue by SDUBZ** [shedaniel/Materialisation#16]
this the issue gist i made with log and mod list etc due to many class conflicts https://gist.github.com/SDUBZ/8a121bddf045e26d7234afb321140f29

**Comment by shedaniel** [comment]
I don’t see the log?

**Comment by SDUBZ** [comment]
heres the log http://puu.sh/E5m1s/2ccd8cb08e.log
