### ISSUE TITLE
0.6.0 crash on startup (problem with REI?)

### ISSUE THREAD

**Issue by abracadabramods** [shedaniel/Materialisation#17]
[crash-2019-08-18_15.22.17-client.txt](https://github.com/shedaniel/Materialisation/files/3513646/crash-2019-08-18_15.22.17-client.txt)

**Comment by cryum** [comment]
[crash-2019-08-19_20.32.30-client.txt](https://github.com/shedaniel/Materialisation/files/3515886/crash-2019-08-19_20.32.30-client.txt)

doesn't look like REI, I didn't have it up and it still crashed.

**Comment by shedaniel** [comment]
Fixed in 0.6.1
