### ISSUE TITLE
Crash when putting material and pattern into preparer

### ISSUE THREAD

**Issue by XerorBattler** [shedaniel/Materialisation#19]
When I put second ingredient (pattern + material or vice versa) into preparer then game crashes

https://pastebin.com/MCSt6FyL

**Comment by shedaniel** [comment]
Can't reproduce, what items did you put? What material packs are you using? Full log?

**Comment by XerorBattler** [comment]
So, I tested it little more. I'm using Cotton Resources and when there is none Vanilla material packs it works fine. But when I add for example VanillaDiamond.materialpack then game crashes. 

https://pastebin.com/XdkF3gS8
