### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by XerorBattler** [shedaniel/Materialisation#20]
Sorry to bother you, but latest version 0.7.1 just crashes on startup 😢 

https://pastebin.com/6STccVnY

same setup as before 

fabric-loader-0.6.1
cotton-1.0.0-rc.3
cotton-resources-1.4.1+1.14.4
fabric-api-0.3.2+build.218-1.14
modmenu-1.7.10+build.119
Materialisation-0.7.1

**Comment by shedaniel** [comment]
Fixed in 0.7.2, wait a minute for me to compile it.
