### ISSUE TITLE
Materials from "Install New..." are not working properly. Also, custom configs.

### ISSUE THREAD

**Issue by VVV101** [shedaniel/Materialisation#27]
I am using latest Fabric (0.7.2+build174) and Fabric API (0.4.24 build 279) for Minecraft 1.15.
Mod version is 2.0.0 alpha 3.
All materials I tried to install are not working properly. They are visible in Materialisation mod configurations. But ingame, all installed patterns are uncraftable (Roughly Enough Item shows pattern and empty slot -> item head/stick of that material).
And when I tried to add json, game doesn't react for it at all.
![2019-12-16_12 15 10](https://user-images.githubusercontent.com/35584242/70883677-fa046380-1ffd-11ea-8658-31b3e3c58601.png)
![2019-12-16_12 15 11](https://user-images.githubusercontent.com/35584242/70883681-fb359080-1ffd-11ea-934f-576662284b2f.png)

JSON containment:
```
{
  "enabled": true,
  "toolColor": -1,
  "toolDurability": 1200,
  "miningLevel": 3,
  "enchantability": 20,
  "durabilityMultiplier": 1.2,
  "breakingSpeedMultiplier": 1.2,
  "toolSpeed": 9,
  "attackDamage": 4,
  "name": "minecraft:emerald",
  "materialTranslationKey": "Emerald",
  "bright": true,
  "ingredient": 
	[{
		{
		  "type": "ITEM",
		  "content": "minecraft:emerald"
		},
		"multiplier": 2.0
	}],
  "fullAmount": 200
}
```

**Comment by StriletsGlib** [comment]
I was thinking that using RAA and Materialisation would be interesting idea. But to create script that will take resources from RAA and put them into Materialisation craft mechanic, I need jsons to work.

**Comment by poppyseed0054** [comment]
I am running Fabric 1.15.1 (fabric-api-0.4.27+build.286-1.15). Mod loads fine, but same issue as above with the Diamond and Obsidian recipes not working. Also running latest version of REI ([Fabric 1.15.x] v3.3.5).
[edit] Here is a list of the mods I have loaded:
RoughlyEnoughItems-3.3.5.jar
trapexpansion-1.3.1-fabric1.15.jar
Materialisation-2.2.1.jar
InstantLava_Fabric1.15-1.1.3.jar
PaintZ+1.2.jar
oysters-fabric-0.1.4-1.15.1.jar
RebornCore-1.15-4.1.0+build.67.jar
TechReborn-1.15-3.2.1+build.107.jar
Adorn-1.6.3+1.15.1.jar
modmenu-1.8.3+build.19.jar
fabric-api-0.4.27+build.286-1.15.jar
nomadbooks-0.1.0.jar
Flora-Doubling-1.15.1-1.0.0.jar
LightOverlay-4.1.jar
WI-Zoom-v1.1-MC1.15.jar
Autofish-0.8.5-fabric-mc1.15.jar
InventorySorter-1.6.3.jar
extradoors-1.3.0-1.15.jar
coloredcampfire-1.1.3.jar
mamiyaotaru
fabricmod_VoxelMap-1.9.14_for_1.15.1.jar
diggusmaximus-1.2.2.jar
stockpile-1.1.3+1.15.1.jar
exotic-matter-mc115-1.13.283.jar
exotic-blocks-mc115-0.13.102.jar
fabric-language-kotlin-1.3.61+build.1.jar
Couplings-1.3.1.jar
yet-another-gravestone-mod-1.0.0.jar
bigbuckets-1.0.0.jar
terrestria-1.1.1+build.18.jar
Hwyla-fabric-1.15-pre4-1.9.19-70.jar
tooltipwrap-1.0.2.jar

**Comment by unmellow** [comment]
good to see this is a known issue does it exist in older versions?

**Comment by shedaniel** [comment]
This has not been looked into, I recently don't have time to look at Materialisation.

**Comment by unmellow** [comment]
fair enough btw i tried manually editing it to fix it so i think only the defualt items have crafting recipe's thanks for making this mod btw

**Comment by shedaniel** [comment]
The json on the first comment is not a valid json, I am still looking into it right now.

**Comment by shedaniel** [comment]
I can reproduce the issue, fixing right away

**Comment by unmellow** [comment]
for me matrialization packs download through the config menu don't get detected at all anymore

**Comment by unmellow** [comment]
i downgraded to 2.0.0 alpha 3 and it works is 2.4.0 only for 1.16?

**Comment by unmellow** [comment]
so if i manually extract the installed the matirialpacks and move the material.json out to the material folder i can get it to work but now 
it says it takes 32 diamonds to make one pickaxe it's the same for every other material in the game

edit: after clicking around it now says it only takes 2 diamond to make a pickaxe head whatever happend is a random bug i can't reproduce

**Comment by shedaniel** [comment]
Ah I see the issue, fixing it again.

**Comment by unmellow** [comment]
thanks that was quick
edit: can confirm everything works
