### ISSUE TITLE
Materialising table sees through walls

### ISSUE THREAD

**Issue by Trnrr** [shedaniel/Materialisation#28]
Im sure this is known but if you place the materialising table against a wall it glitches and shows xray.
![2019-12-18_21 39 10](https://user-images.githubusercontent.com/20446954/71143146-24f9dd80-21df-11ea-99e3-a74e80fa668c.png)

**Comment by Daktyl198** [comment]
Another example: 
![2019-12-24_04 11 32](https://user-images.githubusercontent.com/2475672/71405564-cc25ad00-2603-11ea-98a6-e73aae094630.png)

**Comment by shedaniel** [comment]
Fixed in 2.1.1
