### ISSUE TITLE
Issue with the tools.

### ISSUE THREAD

**Issue by sheryboy77** [shedaniel/Materialisation#29]
There is this bug that when you pick up a tool made from the mod this happnes.  
![20200221_160020](https://user-images.githubusercontent.com/61315271/75030168-5f287980-54c5-11ea-9a15-2f03c8181715.jpg)
![20200221_160012](https://user-images.githubusercontent.com/61315271/75030175-62bc0080-54c5-11ea-82af-30236d419ed0.jpg)
![20200221_160036](https://user-images.githubusercontent.com/61315271/75030180-6485c400-54c5-11ea-9536-9b6c5eade5f0.jpg)
![20200221_160027](https://user-images.githubusercontent.com/61315271/75030184-66e81e00-54c5-11ea-9dd5-c957bdfa2be2.jpg)
![20200221_160103](https://user-images.githubusercontent.com/61315271/75030187-68b1e180-54c5-11ea-9561-ce30eb6153a1.jpg)
 #![20200221_160009](https://user-images.githubusercontent.com/61315271/75030192-6a7ba500-54c5-11ea-8f00-e4d66bd586fa.jpg)

I am using the latest version which is v2.2.1 and I am using It on minecraft 1.15.2

**Comment by shedaniel** [comment]
Can't reproduce, can you share logs or try it with latest version (v2.3.0)

**Comment by shedaniel** [comment]
Fixed
