### ISSUE TITLE
Delay when breaking a block with a materialised tool on server

### ISSUE THREAD

**Issue by LemmaEOF** [shedaniel/Materialisation#3]
When breaking a block using a materialised tool, the block will react like there's TPS lag; it will disappear, reappear for a second, then disappear again and drop the item. I've seen this happen on a server when vanilla tools don't have any delay like it. Using version 0.3.2 on 1.14.3 with Fabric API 0.3.0+188.

**Comment by shedaniel** [comment]
Can reproduce on server.
