### ISSUE TITLE
Crashes on startup (MC version 20w13b, mod version 2.4.1)

### ISSUE THREAD

**Issue by The-Dark-Catto** [shedaniel/Materialisation#31]
[crash-2020-03-30_15.54.26-client.txt](https://github.com/shedaniel/Materialisation/files/4405198/crash-2020-03-30_15.54.26-client.txt)

MC Version: 20w13b
Fabric loader version: 0.5.2.39
Mod version: 2.4.1

**Comment by shedaniel** [comment]
1.16 are not supported yet.
