### ISSUE TITLE
Cant see textures

### ISSUE THREAD

**Issue by ExonHUN** [shedaniel/Materialisation#37]
![image](https://user-images.githubusercontent.com/59777466/88553813-0043cf00-d026-11ea-8828-7e1931d8ce72.png)

**Comment by shedaniel** [comment]
sodium or optifine not compatible

**Comment by natsistd** [comment]
> sodium or optifine not compatible

I was having the same issue. Is this something that needs to be fixed on Sodium's end?

**Comment by shedaniel** [comment]
Correct, sodium doesn't support fabric rendering api, in turns breaks rendering of materialisation's dynamic tools

**Comment by shedaniel** [comment]
Caused by https://github.com/jellysquid3/sodium-fabric/issues/5
