### ISSUE TITLE
Cotton Resources materials cannot be used to make parts on the Material Preparer

### ISSUE THREAD

**Issue by natsistd** [shedaniel/Materialisation#38]
I have the Cotton Resources mod installed. It successfully adds new ores to world generation. When I try to use the ingot made from these new ores (Cobalt for example), it does not allow me to create any tool parts using the pattern on the Material Preparer. 

Screenshot: https://i.imgur.com/a4WIynB.png

**Comment by shedaniel** [comment]
Will look into it.
