### ISSUE TITLE
Spam in Console log 1.16.2

### ISSUE THREAD

**Issue by furtabs** [shedaniel/Materialisation#44]
I used the json to destroy the json.

**Comment by shedaniel** [comment]
what are you on about

**Comment by LlubNek** [comment]
He's probably talking about this error message:
```
ps stderr: Sep 29, 2020 12:32:36 PM net.devtech.arrp.ARRP onPreLaunch
SEVERE: I used the json to destroy the json
```

No idea if that error is actually coming from materialisation or not, but here's a log:
[latest.log](https://github.com/shedaniel/Materialisation/files/5300528/latest.log)

**Comment by LlubNek** [comment]
Seems it was materialisation.

**Comment by shedaniel** [comment]
just ignore it, it is one line

**Comment by LlubNek** [comment]
This can be a bit of a problem though since it can mask other errors that occur later.  GD Launcher will list this as the cause of a crash for example.
