### ISSUE TITLE
Compatability issues with MoreEnchantments

### ISSUE THREAD

**Issue by John-Paul-R** [shedaniel/Materialisation#5]
In my testing, the "Veinminer" enchantment from MoreEnchantments applies to Materialization pickaxes, but the ability does not activate when an applicable block is broken. (Normal MC enchants and the mod's "Autosmelt" do work with them, however). I've looked through the sources of both mods, it seems that the issue has to do with the way Materialization handles durability/damage (it uses a custom system that I believe deprecates and/or replaces the default methods). When ProtectItemFromBreaking was set to false, Veinminer worked with the Materialization pickaxe, but the pickaxe then immediately broke.

I believe the thing that stops veinminer from working is the "ProtectItemFromBreaking" condition on line 164 in `moenchants.Logic.onBreakMixinLogic`:
```java
MoEnchantmentsMod.config.ProtectItemFromBreaking ? tool.getDurability() > 2 : true)
```
The only `getDurability()` method I could find in Materialization was `MaterializationUtils.getDurability()`, so my assumption is that adding implementation for that method (perhaps just calling & returning the output from `MaterializationUtils.getToolDurability()`) should resolve this issue.

**Comment by John-Paul-R** [comment]
Update: I'm fairly certain that my proposed fix will not work, as the `MaterializationUtils.getDurability()` method I referenced is not an instance method of the `ItemStack` class (the variable `tool` is of type ItemStack). ~~Perhaps this method should be added to `items.MaterializedMiningTool` (or classes that implement it) directly?~~ Edit: I misunderstood how those classes operate.

**Comment by shedaniel** [comment]
I can try to go over it tomorrow.

**Comment by John-Paul-R** [comment]
Upon testing again, I found that while the exact issue mentioned above no longer occurs, a new one has been introduced. Veinminer now properly activates for Materialisation pickaxes, but the way that the durability is set after the action is complete is broken. The durability (`mt_durability` tag) is set to the difference between the tool's durability value at the time it broke the block and its max durability. Ex: if you have a materialized iron pickaxe (max durability 250) at durability 240, and veinmine with it, its durability will then be set to 10. This results in instant pickaxe breakage if veinmining occurs at max durability.

I believe this may be in some way caused by the fact that MoreEnchantments calls the method: `ItemStack.damage()`, which does not have an implementation in Materialisation's durability system, but I am not sure.

**Comment by John-Paul-R** [comment]
This issue seems to be resolved in the latest update.

**Comment by shedaniel** [comment]
Yep it should be
