### ISSUE TITLE
Blank texture for tools

### ISSUE THREAD

**Issue by GiraffeSummer** [shedaniel/Materialisation#52]
No images are loading for the tools
This is what I have in my inventory
![image](https://user-images.githubusercontent.com/39410674/100734777-7be8ca80-33d0-11eb-8b35-425108990914.png)

I used to have about 10-20 pages empty in REI as well, I think this was fixed by installing a pack (I thought I might be missing something) but that just seemed to remove them from the REI menu

**Comment by shedaniel** [comment]
Are you using sodium, if so, it is incompatible.

**Comment by GiraffeSummer** [comment]
Oh yeah, that was the problem, thanks!
will it ever be compatible?

**Comment by shedaniel** [comment]
go ask sodium
