### ISSUE TITLE
Compatability issue with NetherOres (Mining)

### ISSUE THREAD

**Issue by John-Paul-R** [shedaniel/Materialisation#7]
Materialized pickaxes do not appear to be effective on NetherOres from the [NetherThings](https://github.com/Brandcraf06/NetherThings) mod. They mine as slow as fists and do not drop resources on break. I am not currently sure if this is an issue with the way Materialisation determines which blocks its tools are effective on, or with the block properties defined in NetherThings. Will update this issue if/when I have more info.

**Comment by shedaniel** [comment]
Oops maybe the latest updates broke the patch.
